image: maven:3.5.3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

build:
  stage: build
  script:
  - 'mvn --batch-mode clean verify'
  except:
  - javadoc

pages:
  stage: deploy
  script:
  - 'mvn --batch-mode clean verify'
  - 'mkdir public'
  - 'mv target/site/apidocs public/apidocs'
  artifacts:
    paths:
    - public
  only:
  - javadoc
